from facebook import *
from settings import *

## 初始化爬蟲
fb = Facebook(FB_EMAIL, FB_PASSWORD, 'Chrome', CHROMEDRIVER_BIN, True)

DISCOVER_ACTION = 'discover'
UPDATE_ACTION = 'update'
GROUP_SITE_TYPE = 'fb_public_group'
PAGE_SITE_TYPE = 'fb_page'
DISCOVER_TIMEOUT = 60*60
UPDATE_TIMEOUT = 60*10
UPDATE_CRAWLER_TIMEOUT = UPDATE_TIMEOUT - 60*1
DEFAULT_IS_LOGINED = False
DEFAULT_IS_HEADLESS = True
DEFAULT_MAX_AMOUNT_OF_ITEMS = 1
DEFAULT_CPU = 2
DEFAULT_N_AMOUNT_IN_A_CHUNK = 10
ITEM_PROCESS_COUNTDOWN_DESCRIPTION = 'Item Process Countdown'
TAKE_A_BREAK_COUNTDOWN_DESCRIPTION = 'Take A Break Countdown'
DEFAULT_BREAK_BETWEEN_PROCESS = 60*2
DEFAULT_MAX_AUTO_TIMES = 0
DEFAULT_MAX_TRY_TIMES = 10
STATUS_SUCCESS = 'SUCCESS'
STATUS_FAILED = 'FAILED'
DEFAULT_SHOULD_USE_ORIGINAL_URL = False
DEFAULT_NEXT_SNAPSHOT_AT_INTERVAL = 60*60*24*3
DEFAULT_SHOULD_LOAD_COMMENT = True
DEFAULT_SHOULD_TURN_OFF_COMMENT_FILTER = True
